12 check animation on hover item in menu
Marcelin97/LoisMarcelin_3_04042021 pull request #23
Opened 2021-05-14 20:56 UTC by Marcelin97

close #12

2021-05-16 06:44 UTC, Tutt-J requested changes

2021-05-16 06:44 UTC, Tutt-J commented on assets/scss/home.scss
> +  animation: hidden 0s ease-in-out forwards;
Why 0 ?

2021-05-16 06:44 UTC, Tutt-J commented on assets/scss/menu.scss
> +      transition-duration: 0.7s;
combine property

2021-05-16 06:44 UTC, Tutt-J commented on assets/scss/menu.scss
> +      transition-property: width;
why not height 100% ?

2021-05-16 20:05 UTC, Marcelin97 commented on assets/scss/home.scss
> +  animation: hidden 0s ease-in-out forwards;
to work without constant loading.

2021-05-16 20:22 UTC, Marcelin97 commented on assets/scss/menu.scss
> +      transition-property: width;
add height

2021-05-16 20:23 UTC, Marcelin97 commented on assets/scss/menu.scss
> +      transition-duration: 0.7s;
i use transition property.

2021-05-17 08:50 UTC, Tutt-J approved these changes

2021-05-17 08:50 UTC, merged